# yaml-language-server: $schema=https://github.com/epics-containers/ioc-template-example/releases/download/3.5.1/ibek.ioc.schema.json

# TODO replace above with the generic IOC schema this IOC is based on
ioc_name: "{{ _global.get_env('IOC_NAME') }}"

description: REPLACE WITH DESCRIPTION

entities:

  - type: epics.EpicsEnvSet
    name: EPICS_TS_MIN_WEST
    value: '0'

  - type: devIocStats.iocAdminSoft
    IOC: '{{ ioc_name | upper }}'

  - type: epics.EpicsCaMaxArrayBytes
    max_bytes: 9000000

  - type: ADAndor3.andor3
    ADDR: 0
    BUFFERS: 50000
    P: BL99P-EA-DET-01
    PORT: ZYLA.CAM
    R: ':CAM:'
    SCANRATE: .1 second
    SET_SDK_ENV: 'True'
    TIMEOUT: 1
    ANDOR_SDK3: -|
      SDK PATH HERE

  - type: ADCore.NDPosPlugin
    NDARRAY_PORT: ZYLA.CAM
    P: BL99P-EA-DET-01
    PORT: POS
    R: ':POS:'
