# this PVC is used to hold the proprietary libraries from the Andor3SDK
# that are loaded at runtime by the IOC

# for the moment we manually deploy this with kubectl but will make it
# part of the ioc deployment workflow in the future (with an init container
# or maybe host script to load the libraries from a specified location)

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: p99-ea-ioc-01-libraries
  labels:
    app: bl99p-ea-ioc-01
    ioc_group: p99
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: p99-ea-ioc-01-libraries-loader
  labels:
    app: bl99p-ea-ioc-01
    ioc_group: p99
spec:
  containers:
    - name: myapp
      image: busybox
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: mypvc
          mountPath: /data
      command: ["sleep", "infinity"]
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: p99-ea-ioc-01-libraries
