# yaml-language-server: $schema=https://github.com/epics-containers/ioc-pmac/releases/download/2024.1.2/ibek.ioc.schema.json


# TODO replace above with the generic IOC schema this IOC is based on
ioc_name: "{{ _global.get_env('IOC_NAME') }}"

description: Motion ioc

entities:
  - type: epics.EpicsEnvSet
    name: EPICS_TZ
    value: GMT0BST

  - type: devIocStats.iocAdminSoft
    IOC: "{{ ioc_name | upper }}"

  # - todo: Add more entities to make a meaningful IOC
  
  - type: epics.EpicsEnvSet
    name: EPICS_TS_MIN_WEST
    value: '0'

  - type: devIocStats.iocAdminSoft
    IOC: '{{ ioc_name | upper }}'

  - type: epics.EpicsCaMaxArrayBytes
    max_bytes: 32000000

  # - type: utility.pingWait
  #   ip: 10.177.2.1
  #   name: BRICK1_PING

  - type: pmac.pmacAsynIPPort
    IP: 10.177.2.1:1025
    name: BRICK01PORT

  - type: pmac.GeoBrick
    MovingPoll: 50
    P: BL99P-MO-STEP-01
    name: BRICK01
    pmacAsynPort: BRICK01PORT

  - type: pmac.GeoBrickTrajectoryControl
    NPOINTS: 100000
    PmacController: BRICK01

  - type: pmac.dls_pmac_asyn_motor
    ACCL: 0.1
    ADDR: 1
    Controller: BRICK01
    DESC: Sample Z
    DHLM: 7
    DIR: Pos
    DLLM: -7
    EGU: mm
    FOFF: Variable
    M: :Z
    MRES: -2e-05
    P: BL99P-MO-STAGE-02
    PREC: 3
    TWV: 0.001
    UEIP: No
    VELO: 1.8

  - type: pmac.dls_pmac_asyn_motor
    ACCL: 0.1
    ADDR: 2
    Controller: BRICK01
    DESC: Sample X
    DHLM: 7
    DIR: Pos
    DLLM: -7
    EGU: mm
    FOFF: Variable
    M: :X
    MRES: -2e-05
    P: BL99P-MO-STAGE-02
    PREC: 3
    TWV: 0.001
    UEIP: No
    VELO: 1.8

  - type: pmac.dls_pmac_asyn_motor
    ACCL: 0.1
    ADDR: 3
    Controller: BRICK01
    DESC: Sample Y
    DHLM: 7
    DIR: Pos
    DLLM: -7
    EGU: mm
    FOFF: Variable
    M: :Y
    MRES: 2e-05
    P: BL99P-MO-STAGE-02
    PREC: 3
    TWV: 0.001
    UEIP: No
    VELO: 1.8

  - type: pmac.pmacDisableLimitsCheck
    Axis: 1
    Controller: BRICK01

  - type: pmac.pmacDisableLimitsCheck
    Axis: 2
    Controller: BRICK01

  - type: pmac.pmacDisableLimitsCheck
    Axis: 3
    Controller: BRICK01

  - type: pmac.autohome
    GRP2: F Lens
    P: BL99P-MO-STAGE-01
    PLC: 11
    PmacController: BRICK01

  - type: pmac.autohome
    GRP2: Z
    GRP3: X
    GRP4: Y
    P: BL99P-MO-STAGE-02
    PLC: 12
    PmacController: BRICK01

  - type: pmac.CS
    CS: 1
    PmacController: BRICK01
    name: BRICK1.CS1

  - type: pmac.CS
    CS: 2
    PmacController: BRICK01
    name: BRICK01.CS2

  - type: pmac.dls_pmac_asyn_motor
    ACCL: 0.1
    ADDR: 7
    Controller: BRICK01.CS2
    DESC: Sample X Lab
    DHLM: 7
    DIR: Pos
    DLLM: -7
    EGU: mm
    FOFF: Variable
    HOMEVIS: 0
    HOMEVISSTR: This is a virtual motor
    M: :LAB:X
    MRES: 0.0001
    P: BL99P-MO-STAGE-02
    PREC: 3
    TWV: 0.1
    UEIP: No
    VELO: 17
    is_cs: true

  - type: pmac.dls_pmac_asyn_motor
    ACCL: 0.1
    ADDR: 8
    Controller: BRICK01.CS2
    DESC: Sample Y Lab
    DHLM: 7
    DIR: Pos
    DLLM: -7
    EGU: mm
    FOFF: Variable
    HOMEVIS: 0
    HOMEVISSTR: This is a virtual motor
    M: :LAB:Y
    MRES: 0.0001
    P: BL99P-MO-STAGE-02
    PREC: 3
    TWV: 0.1
    UEIP: No
    VELO: 17
    is_cs: true

  - type: pmac.dls_pmac_asyn_motor
    ACCL: 0.1
    ADDR: 9
    Controller: BRICK01.CS2
    DESC: Sample Z Lab
    DHLM: 7
    DIR: Pos
    DLLM: -7
    EGU: mm
    FOFF: Variable
    HOMEVIS: 0
    HOMEVISSTR: This is a virtual motor
    M: :LAB:Z
    MRES: 0.0001
    P: BL99P-MO-STAGE-02
    PREC: 3
    TWV: 0.1
    UEIP: No
    VELO: 17
    is_cs: true

  - type: pmac.pmacCreateCsGroup
    AxisCount: 3
    Controller: BRICK01
    GroupName: StraightThrough
    GroupNumber: 1

  - type: pmac.pmacCreateCsGroup
    AxisCount: 3
    Controller: BRICK01
    GroupName: J13Kinematics
    GroupNumber: 2

  - type: pmac.pmacCsGroupAddAxis
    AxisDef: Z
    AxisNumber: 1
    Controller: BRICK01
    CoordSysNumber: 1
    GroupNumber: 1

  - type: pmac.pmacCsGroupAddAxis
    AxisDef: X
    AxisNumber: 2
    Controller: BRICK01
    CoordSysNumber: 1
    GroupNumber: 1

  - type: pmac.pmacCsGroupAddAxis
    AxisDef: Y
    AxisNumber: 3
    Controller: BRICK01
    CoordSysNumber: 1
    GroupNumber: 1

  - type: pmac.pmacCsGroupAddAxis
    AxisDef: I
    AxisNumber: 1
    Controller: BRICK01
    CoordSysNumber: 2
    GroupNumber: 2

  - type: pmac.pmacCsGroupAddAxis
    AxisDef: I
    AxisNumber: 2
    Controller: BRICK01
    CoordSysNumber: 2
    GroupNumber: 2

  - type: pmac.pmacCsGroupAddAxis
    AxisDef: I
    AxisNumber: 3
    Controller: BRICK01
    CoordSysNumber: 2
    GroupNumber: 2

  - type: pmac.pmacVariableWrite
    EGU: deg
    P: BL99P-MO-STAGE-01
    PORT: BRICK01
    Q: :WRITETHETA
    VAR: '&2Q21'
    VARIABLE_PREC: 4

  - type: pmac.pmacVariableWrite
    EGU: deg
    P: BL99P-MO-STAGE-01
    PORT: BRICK01
    Q: :WRITEPITCH
    VAR: '&2Q20'
    VARIABLE_PREC: 4

  - type: pmac.pmacVariableWrite
    EGU: deg
    P: BL99P-MO-STAGE-01
    PORT: BRICK01
    Q: :WRITEROLL
    VAR: '&2Q22'
    VARIABLE_PREC: 4