# yaml-language-server: $schema=file:///tmp/schema.json

ioc_name: "{{ _global.get_env('IOC_NAME') }}"

description: Example TetrAMM for BL99P

entities:
  - type: quadEM.TetrAMM
    PORT: XBPM1.DRV
    P: BL99P-EA-XBPM-01
    R: ":DRV:"
    QSIZE: 20
    IP: "172.23.177.144:10001" # TODO: replace with actual IP

  - type: quadEM.Plugins
    DEVICE: XBPM1.DRV
    PORTPREFIX: XBPM1
    STAT_NCHAN: 1000
    STAT_XSIZE: 10000

  - type: ADCore.NDFileHDF5
    ADDR: 0
    BLOCK: 0
    ENABLED: 1
    NDARRAY_PORT: XBPM1.DRV
    P: BL99P-EA-XBPM-01
    PORT: XBPM1.pos
    QUEUE: 1000
    R: ':HDF5:'
    TIMEOUT: 1